server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xml_trial_database
    username: xml_trial_user
    password: xml_trial_password
  jpa:
    hibernate:
      ddl-auto: update